### ISSUE TITLE
La información sobre si alguien es rey no se usa

### ISSUE THREAD

**Issue by angelgcuartero** [paradigmadigital/python-challenge#1]
Estaba revisando el reto y quitando la condición de que sólo puede haber un rey en un lugar, no se utiliza para nada público la información de si alguien es rey, o por lo menos no consigo verlo. A lo mejor cuando se solicite la info del 3º ms debería devolver si alguno de los personajes es el rey del territorio.

**Comment by avara1986** [comment]
Buenas, los ejemplos que se muestran de las APIs son aproximaciones para orientar como modelarlas, pero cada uno puede incluir o quitar lo que vea conveniente  :smiley:
